FROM rust:1.93.1-bookworm

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    pkg-config \
    libssl-dev \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN cargo install cargo-watch --locked

CMD ["/usr/local/cargo/bin/cargo", "watch", "-x", "run"]
